# SPDX-License-Identifier: GPL-3.0-or-later
"""
Linear-elastic FEA on a regular voxel grid.

8-node trilinear hexahedral elements, all identical in shape, so we build the
element stiffness matrix KE once and run a *matrix-free* conjugate-gradient
solve: K*u is evaluated element-by-element with vectorised numpy, never
assembling a global sparse matrix (keeps us scipy-free).

The solve is restricted to elements that actually exist (inside the build
space): only their nodes get DOFs, so empty margin around the part costs
nothing. Optionally runs on the GPU via CuPy.

DOF numbering (original/full space): node n has DOFs [3n, 3n+1, 3n+2].
Grid nodes: (nx+1)*(ny+1)*(nz+1) for an nx*ny*nz element grid.
"""

import numpy as np


# ---------------------------------------------------------------------------
# Element stiffness matrix (unit cube, generated by Gauss quadrature)
# ---------------------------------------------------------------------------

def _hex8_KE(E=1.0, nu=0.3):
    """24x24 stiffness for a unit cube, isotropic material."""
    nodes = np.array([
        [-1, -1, -1], [1, -1, -1], [1, 1, -1], [-1, 1, -1],
        [-1, -1, 1], [1, -1, 1], [1, 1, 1], [-1, 1, 1],
    ], dtype=float)

    c = E / ((1 + nu) * (1 - 2 * nu))
    C = c * np.array([
        [1 - nu, nu, nu, 0, 0, 0],
        [nu, 1 - nu, nu, 0, 0, 0],
        [nu, nu, 1 - nu, 0, 0, 0],
        [0, 0, 0, (1 - 2 * nu) / 2, 0, 0],
        [0, 0, 0, 0, (1 - 2 * nu) / 2, 0],
        [0, 0, 0, 0, 0, (1 - 2 * nu) / 2],
    ])

    g = 1.0 / np.sqrt(3.0)
    gp = [-g, g]
    KE = np.zeros((24, 24))
    for xi in gp:
        for eta in gp:
            for zeta in gp:
                dN = np.zeros((3, 8))
                for i, (a, b, c_) in enumerate(nodes):
                    dN[0, i] = a * (1 + b * eta) * (1 + c_ * zeta) / 8.0
                    dN[1, i] = b * (1 + a * xi) * (1 + c_ * zeta) / 8.0
                    dN[2, i] = c_ * (1 + a * xi) * (1 + b * eta) / 8.0
                J = np.array([[0.5, 0, 0], [0, 0.5, 0], [0, 0, 0.5]])
                detJ = np.linalg.det(J)
                dNxyz = np.linalg.solve(J, dN)
                B = np.zeros((6, 24))
                for i in range(8):
                    bx, by, bz = dNxyz[:, i]
                    c0 = 3 * i
                    B[0, c0] = bx
                    B[1, c0 + 1] = by
                    B[2, c0 + 2] = bz
                    B[3, c0] = by; B[3, c0 + 1] = bx
                    B[4, c0 + 1] = bz; B[4, c0 + 2] = by
                    B[5, c0] = bz; B[5, c0 + 2] = bx
                KE += (B.T @ C @ B) * detJ
    return KE


# ---------------------------------------------------------------------------
# Element <-> global DOF connectivity
# ---------------------------------------------------------------------------

def _node_id(ix, iy, iz, nx, ny):
    return ix + (nx + 1) * (iy + (ny + 1) * iz)


def build_edof(nx, ny, nz):
    """Return edofMat [nelem, 24] of global DOF indices per element."""
    ex, ey, ez = np.meshgrid(
        np.arange(nx), np.arange(ny), np.arange(nz), indexing='ij')
    ex = ex.ravel(); ey = ey.ravel(); ez = ez.ravel()
    offs = [(0, 0, 0), (1, 0, 0), (1, 1, 0), (0, 1, 0),
            (0, 0, 1), (1, 0, 1), (1, 1, 1), (0, 1, 1)]
    edof = np.empty((ex.size, 24), dtype=np.int64)
    for k, (ox, oy, oz) in enumerate(offs):
        nid = _node_id(ex + ox, ey + oy, ez + oz, nx, ny)
        edof[:, 3 * k] = 3 * nid
        edof[:, 3 * k + 1] = 3 * nid + 1
        edof[:, 3 * k + 2] = 3 * nid + 2
    return edof


# ---------------------------------------------------------------------------
# Optional GPU backend
# ---------------------------------------------------------------------------

def _gpu_backend():
    """Return the cupy module if a CUDA device is usable, else None."""
    try:
        import cupy as cp
        if cp.cuda.runtime.getDeviceCount() < 1:
            return None
        return cp
    except Exception:
        return None


_GPU_OK = None


def _gpu_self_test():
    """Solve a tiny problem on CPU and GPU; return True only if they agree.

    This guards against any CuPy/driver quirk silently producing a wrong FEA
    result. If it fails, the GPU is never used and we stay on the proven CPU
    path (so results are always correct, just maybe slower).
    """
    if _gpu_backend() is None:
        return False
    try:
        nx, ny, nz = 6, 3, 3

        def nid(ix, iy, iz):
            return ix + (nx + 1) * (iy + (ny + 1) * iz)

        fixed = []
        for iy in range(ny + 1):
            for iz in range(nz + 1):
                n = nid(0, iy, iz)
                fixed += [3 * n, 3 * n + 1, 3 * n + 2]
        f = np.zeros(3 * (nx + 1) * (ny + 1) * (nz + 1))
        for iy in range(ny + 1):
            n = nid(nx, iy, 0)
            f[3 * n + 2] = -1.0
        Evec = np.ones(nx * ny * nz)

        cpu = VoxelFEA(nx, ny, nz, use_gpu=False)
        cpu.set_fixed(fixed)
        gpu = VoxelFEA(nx, ny, nz, use_gpu=True, _skip_validate=True)
        gpu.set_fixed(fixed)
        if not gpu.gpu:
            return False
        uc = cpu.solve(Evec, f, tol=1e-8)
        ug = gpu.solve(Evec, f, tol=1e-8)
        return bool(np.allclose(uc, ug, rtol=1e-3, atol=1e-9))
    except Exception:
        return False


def gpu_usable():
    """Cached: True only if CuPy is present AND passes the CPU/GPU self-test."""
    global _GPU_OK
    if _GPU_OK is None:
        _GPU_OK = _gpu_self_test()
    return _GPU_OK


def gpu_available():
    """Back-compat alias: only reports usable (validated) GPU."""
    return gpu_usable()


def gpu_status():
    """Human-readable GPU status for the UI."""
    if _gpu_backend() is None:
        return "GPU: CuPy not installed - using CPU"
    if gpu_usable():
        return "GPU: CuPy ready (validated)"
    return "GPU: self-test FAILED - using CPU"


# ---------------------------------------------------------------------------
# Matrix-free solver (restricted to active elements)
# ---------------------------------------------------------------------------

class VoxelFEA:
    """Solves K(rho) u = f matrix-free over the active (build-space) elements.

    active_elems : optional bool mask (nelem,). Only these elements - and the
    nodes they touch - enter the linear system, so empty space around the part
    is skipped entirely. The public API still speaks the full DOF space:
    solve() returns a full-length u and element_strain_energy() returns a full
    per-element array (zeros outside the active region).
    """

    def __init__(self, nx, ny, nz, nu=0.3, e_min=1e-9, use_gpu=False,
                 active_elems=None, _skip_validate=False):
        self.nx, self.ny, self.nz = nx, ny, nz
        self.nelem = nx * ny * nz
        self.ndof_full = 3 * (nx + 1) * (ny + 1) * (nz + 1)
        self.e_min = e_min
        self.KE = _hex8_KE(E=1.0, nu=nu)
        self.edof_full = build_edof(nx, ny, nz)        # full, original DOFs

        if active_elems is None:
            self.active_elems = np.ones(self.nelem, dtype=bool)
        else:
            self.active_elems = np.asarray(active_elems, dtype=bool).ravel()

        # Compress to the DOFs actually used by active elements.
        edof_a = self.edof_full[self.active_elems]      # (na, 24) original DOFs
        used = np.unique(edof_a)
        remap = -np.ones(self.ndof_full, dtype=np.int64)
        remap[used] = np.arange(used.size)
        self.used_dofs = used
        self.remap = remap
        self.ndof = int(used.size)                       # reduced size
        self.edof = remap[edof_a]                        # (na, 24) reduced DOFs

        self.free = None
        self._diag = None

        # GPU setup - only if requested AND validated by the self-test.
        self.gpu = False
        self.xp = np
        self.KE_x = self.KE
        self.edof_x = self.edof
        if use_gpu and (_skip_validate or gpu_usable()):
            cp = _gpu_backend()
            if cp is not None:
                try:
                    self.xp = cp
                    self.KE_x = cp.asarray(self.KE)
                    self.edof_x = cp.asarray(self.edof)
                    self.gpu = True
                except Exception:
                    self.xp = np; self.gpu = False
                    self.KE_x = self.KE; self.edof_x = self.edof

    def set_fixed(self, fixed_dofs):
        """fixed_dofs: original global DOF indices to constrain."""
        free = np.ones(self.ndof, dtype=bool)
        fd = self.remap[np.asarray(fixed_dofs, dtype=np.int64)]
        fd = fd[fd >= 0]
        free[fd] = False
        self.free = free

    def _Evec_active(self, Evec_full):
        return np.asarray(Evec_full, dtype=float)[self.active_elems]

    def _apply_K(self, u, Evec_a):
        # BLAS matmul (KE is symmetric) then a bincount scatter-add. Both numpy
        # and cupy provide bincount with the same semantics, so CPU and GPU run
        # identical, well-tested code (no scatter_add quirks).
        xp = self.xp
        ue = u[self.edof_x]                                  # (na, 24)
        ke_ue = (ue @ self.KE_x.T) * Evec_a[:, None]
        return xp.bincount(self.edof_x.ravel(),
                           weights=ke_ue.ravel(), minlength=self.ndof)

    def _diagonal(self, Evec_a):
        xp = self.xp
        diagKE = xp.diag(self.KE_x)
        contrib = Evec_a[:, None] * diagKE[None, :]          # (na, 24)
        d = xp.bincount(self.edof_x.ravel(),
                        weights=contrib.ravel(), minlength=self.ndof)
        d = xp.where(d == 0, 1.0, d)
        return d

    def solve(self, Evec, f, tol=1e-4, max_cg=None, x0=None):
        """Preconditioned CG over active DOFs. Returns full-length u (numpy).

        x0 : optional warm-start (full-length numpy) - hugely cuts CG iters
        because the structure changes only slightly between SIMP steps.
        """
        if self.free is None:
            raise RuntimeError("call set_fixed() before solve()")
        xp = self.xp
        free = xp.asarray(self.free)
        Evec_a = xp.asarray(self._Evec_active(Evec))
        f_r = xp.asarray(np.asarray(f, dtype=float)[self.used_dofs])

        self._diag = self._diagonal(Evec_a)
        Minv = 1.0 / self._diag

        if x0 is None:
            u = xp.zeros(self.ndof)
            r = f_r.copy()
        else:
            u = xp.asarray(np.asarray(x0, dtype=float)[self.used_dofs])
            u = xp.where(free, u, 0.0)
            r = f_r - self._apply_K(u, Evec_a)
        r = xp.where(free, r, 0.0)

        z = xp.where(free, Minv * r, 0.0)
        p = z.copy()
        rz = float(r @ z)

        fnorm = float(xp.linalg.norm(xp.where(free, f_r, 0.0)))
        if fnorm == 0:
            u_full = np.zeros(self.ndof_full)
            return u_full
        max_cg = max_cg or 4 * int(self.free.sum())

        for _ in range(max_cg):
            Kp = self._apply_K(p, Evec_a)
            Kp = xp.where(free, Kp, 0.0)
            alpha = rz / float(p @ Kp)
            u = u + alpha * p
            r = r - alpha * Kp
            if float(xp.linalg.norm(xp.where(free, r, 0.0))) / fnorm < tol:
                break
            z = xp.where(free, Minv * r, 0.0)
            rz_new = float(r @ z)
            p = z + (rz_new / rz) * p
            p = xp.where(free, p, 0.0)
            rz = rz_new

        u = xp.where(free, u, 0.0)
        u_r = u if not self.gpu else xp.asnumpy(u)
        u_full = np.zeros(self.ndof_full)
        u_full[self.used_dofs] = u_r
        return u_full

    def element_strain_energy(self, u_full):
        """Per-element u_e^T KE u_e for ALL elements (numpy, length nelem)."""
        u = np.asarray(u_full)
        ce = np.zeros(self.nelem)
        ue = u[self.edof_full[self.active_elems]]
        ke_ue = ue @ self.KE.T
        ce[self.active_elems] = np.einsum('ei,ei->e', ue, ke_ue)
        return ce
